# Generated by Django 2.1.15 on 2020-05-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statut',
            old_name='color',
            new_name='couleur',
        ),
    ]
