# Generated by Django 2.1.15 on 2020-05-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20200521_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'verbose_name': 'tache'},
        ),
        migrations.AlterModelOptions(
            name='statut',
            options={'verbose_name': 'statut'},
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={'verbose_name': 'tache'},
        ),
    ]
