# Generated by Django 2.1.15 on 2020-05-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20200521_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'verbose_name': 'commentaire'},
        ),
    ]
