# Generated by Django 2.1.15 on 2020-05-22 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20200522_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
