# Generated by Django 2.1.15 on 2020-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_auto_20200522_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
